import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import Navbar from "@/components/ui/navbar";
import "./globals.css";



const outfit = Outfit({
  variable :  "--font-outfit",
  subsets : ["latin"]
})


export const metadata: Metadata = {
  title: "landing-page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
          <Navbar/>
        {children}
      </body>
    </html>
  );
}
